# permissions for end users to edit guestbooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: guestbook-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: demo-crd-controller-k8s
    app.kubernetes.io/part-of: demo-crd-controller-k8s
    app.kubernetes.io/managed-by: kustomize
  name: guestbook-editor-role
rules:
- apiGroups:
  - webapp.my.crd.dipankar
  resources:
  - guestbooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.my.crd.dipankar
  resources:
  - guestbooks/status
  verbs:
  - get
